import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { AdminUser, Site } from '../../../core/models/api.models';
import { AdminApiService } from '../../../core/services/admin-api.service';
import { apiErrorMessage } from '../../../core/services/http-error';
import { ToastService } from '../../../core/services/toast.service';
import { ModalAutofocus } from '../../../shared/ui/modal-autofocus';
import { PageState } from '../../../shared/ui/page-state';

@Component({
  selector: 'app-admin-sites', imports: [ReactiveFormsModule, PageState, ModalAutofocus],
  host: { '(document:keydown.escape)': 'closeOverlay()' },
  template: `
    <header class="page-header"><div><span class="eyebrow">Installations</span><h1>Solar sites</h1><p>Connect homeowner accounts to their physical solar installations.</p></div><button class="button button--primary" (click)="openCreate()">Add site</button></header>
    @if (loading()) { <app-page-state kind="loading" title="Loading sites" message="Retrieving solar installations…" /> } @else if (error()) { <app-page-state kind="error" title="Could not load sites" [message]="error()" (retry)="load()" /> } @else if (!sites().length) { <app-page-state kind="empty" title="No solar sites" message="Add an installation before assigning devices or batteries." /> } @else {
      <section class="card-grid">@for (site of sites(); track site.id) { <article class="asset-card"><div class="asset-card__top"><span class="asset-icon" aria-hidden="true">S</span><span [class]="site.active ? 'badge badge--success' : 'badge badge--muted'">{{ site.active ? 'Active' : 'Inactive' }}</span></div><h2>{{ site.name }}</h2><p>{{ site.address || 'No address provided' }}</p><dl><div><dt>Owner</dt><dd>{{ site.ownerName }}</dd></div><div><dt>Code</dt><dd>{{ site.code }}</dd></div><div><dt>Capacity</dt><dd>{{ site.capacityKw }} kW</dd></div></dl><div class="asset-card__actions"><button class="button button--quiet button--small" (click)="openEdit(site)">Edit</button><button class="button button--danger button--small" (click)="confirmDelete.set(site)">Delete</button></div></article> }</section>
    }
    @if (editing()) { <div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><div class="modal__header"><div><span class="eyebrow">Installation record</span><h2>{{ editing()?.id ? 'Edit site' : 'Add solar site' }}</h2></div><button class="icon-button" aria-label="Close" (click)="editing.set(null)">×</button></div><form [formGroup]="form" (ngSubmit)="save()" class="form-grid"><label class="field"><span>Owner</span><select formControlName="ownerId" appModalAutofocus>@for (owner of homeowners(); track owner.id) { <option [value]="owner.id">{{ owner.name }} · {{ owner.email }}</option> }</select></label><label class="field"><span>Site code</span><input formControlName="code" /></label><label class="field"><span>Name</span><input formControlName="name" /></label><label class="field"><span>Capacity (kW)</span><input type="number" min="0.001" step="0.1" formControlName="capacityKw" /></label><label class="field field--wide"><span>Address</span><textarea rows="3" formControlName="address"></textarea></label><label class="check-field field--wide"><input type="checkbox" formControlName="active" /><span>Site is active</span></label><div class="modal__actions field--wide"><button class="button button--secondary" type="button" (click)="editing.set(null)">Cancel</button><button class="button button--primary" type="submit" [disabled]="saving()">{{ saving() ? 'Saving…' : 'Save site' }}</button></div></form></section></div> }
    @if (confirmDelete(); as site) { <div class="modal-backdrop"><section class="modal modal--small" role="alertdialog" aria-modal="true"><h2>Delete {{ site.name }}?</h2><p>Deletion may be prevented while devices, batteries or readings still reference this site.</p><div class="modal__actions"><button class="button button--secondary" (click)="confirmDelete.set(null)">Cancel</button><button class="button button--danger" (click)="remove(site)">Delete site</button></div></section></div> }
  `,
})
export class AdminSites {
  private readonly api = inject(AdminApiService); private readonly toast = inject(ToastService);
  readonly sites = signal<Site[]>([]); readonly homeowners = signal<AdminUser[]>([]); readonly loading = signal(true); readonly saving = signal(false); readonly error = signal(''); readonly editing = signal<Partial<Site> | null>(null); readonly confirmDelete = signal<Site | null>(null);
  readonly form = new FormGroup({ ownerId: new FormControl<number | null>(null, [Validators.required]), code: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(60)] }), name: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(150)] }), address: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(500)] }), capacityKw: new FormControl<number | null>(null, [Validators.required, Validators.min(0.001)]), active: new FormControl(true, { nonNullable: true }) });
  constructor() { this.load(); this.api.users(0, 100).subscribe((result) => this.homeowners.set(result.content.filter((user) => user.role === 'HOMEOWNER'))); }
  load(): void { this.loading.set(true); this.api.sites().subscribe({ next: (result) => { this.sites.set(result.content); this.loading.set(false); }, error: (error: unknown) => { this.error.set(apiErrorMessage(error)); this.loading.set(false); } }); }
  openCreate(): void { this.editing.set({}); this.form.reset({ ownerId: this.homeowners()[0]?.id ?? null, code: '', name: '', address: '', capacityKw: null, active: true }); }
  openEdit(site: Site): void { this.editing.set(site); this.form.reset({ ownerId: site.ownerId, code: site.code, name: site.name, address: site.address ?? '', capacityKw: site.capacityKw, active: site.active }); }
  closeOverlay(): void { this.editing.set(null); this.confirmDelete.set(null); }
  save(): void { this.form.markAllAsTouched(); const value = this.form.getRawValue(); const current = this.editing(); if (this.form.invalid || !current || value.ownerId === null || value.capacityKw === null) return; this.saving.set(true); const request = { ...value, ownerId: value.ownerId, capacityKw: value.capacityKw, address: value.address || null }; const call = current.id ? this.api.updateSite(current.id, request) : this.api.createSite(request); call.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.toast.show(`Site ${current.id ? 'updated' : 'created'}.`, 'success'); this.editing.set(null); this.load(); }, error: (error: unknown) => this.toast.show(apiErrorMessage(error), 'error') }); }
  remove(site: Site): void { this.api.deleteSite(site.id).subscribe({ next: () => { this.toast.show('Site deleted.', 'success'); this.confirmDelete.set(null); this.load(); }, error: (error: unknown) => this.toast.show(apiErrorMessage(error), 'error') }); }
}
