CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    email varchar(254) NOT NULL,
    password varchar(255) NOT NULL,
    role varchar(255) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    phone varchar(30),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'HOMEOWNER'))
);

CREATE INDEX idx_users_role ON users (role);

CREATE TABLE solar_sites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint NOT NULL,
    code varchar(60) NOT NULL,
    name varchar(150) NOT NULL,
    address varchar(500),
    capacity_kw numeric(12, 3) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_solar_sites_code UNIQUE (code),
    CONSTRAINT fk_solar_sites_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_solar_sites_owner ON solar_sites (owner_id);

CREATE TABLE devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier varchar(100) NOT NULL,
    name varchar(150) NOT NULL,
    type varchar(40) NOT NULL,
    status varchar(30) NOT NULL,
    site_id bigint NOT NULL,
    manufacturer varchar(100),
    model varchar(100),
    firmware_version varchar(100),
    last_seen_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_devices_identifier UNIQUE (identifier),
    CONSTRAINT ck_devices_type CHECK (
        type IN ('SOLAR_INVERTER', 'SMART_METER', 'BATTERY_CONTROLLER', 'WEATHER_SENSOR')
    ),
    CONSTRAINT ck_devices_status CHECK (status IN ('ONLINE', 'OFFLINE', 'MAINTENANCE', 'RETIRED')),
    CONSTRAINT fk_devices_site FOREIGN KEY (site_id) REFERENCES solar_sites (id)
);

CREATE INDEX idx_devices_site ON devices (site_id);
CREATE INDEX idx_devices_status ON devices (status);

CREATE TABLE batteries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier varchar(100) NOT NULL,
    name varchar(150) NOT NULL,
    site_id bigint NOT NULL,
    capacity_kwh numeric(12, 3) NOT NULL,
    status varchar(30) NOT NULL,
    current_charge_percent numeric(5, 2) NOT NULL,
    current_stored_energy_kwh numeric(12, 3) NOT NULL,
    last_updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_batteries_identifier UNIQUE (identifier),
    CONSTRAINT ck_batteries_status CHECK (status IN ('ONLINE', 'OFFLINE', 'MAINTENANCE', 'RETIRED')),
    CONSTRAINT fk_batteries_site FOREIGN KEY (site_id) REFERENCES solar_sites (id)
);

CREATE INDEX idx_batteries_site ON batteries (site_id);

CREATE TABLE energy_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id bigint NOT NULL,
    device_id bigint NOT NULL,
    production_kwh numeric(15, 3) NOT NULL,
    consumption_kwh numeric(15, 3) NOT NULL,
    grid_import_kwh numeric(15, 3) NOT NULL,
    grid_export_kwh numeric(15, 3) NOT NULL,
    recorded_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_energy_device_timestamp UNIQUE (device_id, recorded_at),
    CONSTRAINT fk_energy_readings_site FOREIGN KEY (site_id) REFERENCES solar_sites (id),
    CONSTRAINT fk_energy_readings_device FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE INDEX idx_energy_site_time ON energy_readings (site_id, recorded_at);
CREATE INDEX idx_energy_device_time ON energy_readings (device_id, recorded_at);

CREATE TABLE storage_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id bigint NOT NULL,
    battery_id bigint NOT NULL,
    charge_percent numeric(5, 2) NOT NULL,
    stored_energy_kwh numeric(12, 3) NOT NULL,
    recorded_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_storage_battery_timestamp UNIQUE (battery_id, recorded_at),
    CONSTRAINT fk_storage_readings_site FOREIGN KEY (site_id) REFERENCES solar_sites (id),
    CONSTRAINT fk_storage_readings_battery FOREIGN KEY (battery_id) REFERENCES batteries (id)
);

CREATE INDEX idx_storage_site_time ON storage_readings (site_id, recorded_at);
CREATE INDEX idx_storage_battery_time ON storage_readings (battery_id, recorded_at);

CREATE TABLE alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    site_id bigint,
    device_id bigint,
    battery_id bigint,
    type varchar(40) NOT NULL,
    severity varchar(20) NOT NULL,
    message varchar(500) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_alerts_type CHECK (
        type IN ('LOW_BATTERY', 'HIGH_CONSUMPTION', 'LOW_PRODUCTION', 'DEVICE_OFFLINE')
    ),
    CONSTRAINT ck_alerts_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT fk_alerts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_alerts_site FOREIGN KEY (site_id) REFERENCES solar_sites (id),
    CONSTRAINT fk_alerts_device FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT fk_alerts_battery FOREIGN KEY (battery_id) REFERENCES batteries (id)
);

CREATE INDEX idx_alerts_user_created ON alerts (user_id, created_at);
CREATE INDEX idx_alerts_user_read ON alerts (user_id, is_read);
CREATE INDEX idx_alerts_type_created ON alerts (type, created_at);

CREATE TABLE system_settings (
    id bigint PRIMARY KEY,
    low_battery_threshold numeric(5, 2) NOT NULL,
    high_consumption_threshold_kwh numeric(15, 3) NOT NULL,
    low_production_threshold_kwh numeric(15, 3) NOT NULL,
    production_alerts_enabled boolean NOT NULL,
    consumption_alerts_enabled boolean NOT NULL,
    battery_alerts_enabled boolean NOT NULL,
    device_offline_alert_enabled boolean NOT NULL,
    device_offline_threshold_minutes integer NOT NULL,
    email_notifications_enabled boolean NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL DEFAULT 0
);
