import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { Battery, BatteryRequest, BatteryStatus, Site } from '../../../core/models/api.models';
import { AdminApiService } from '../../../core/services/admin-api.service';
import { apiErrorMessage } from '../../../core/services/http-error';
import { ToastService } from '../../../core/services/toast.service';
import { ModalAutofocus } from '../../../shared/ui/modal-autofocus';
import { PageState } from '../../../shared/ui/page-state';

const STATUSES: BatteryStatus[] = ['ONLINE', 'OFFLINE', 'MAINTENANCE', 'RETIRED'];
function localDate(value: string): string { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

@Component({
  selector: 'app-admin-batteries', imports: [ReactiveFormsModule, DatePipe, PageState, ModalAutofocus],
  host: { '(document:keydown.escape)': 'closeOverlay()' },
  template: `
    <header class="page-header"><div><span class="eyebrow">Storage assets</span><h1>Batteries</h1><p>Maintain battery identity, capacity and current operational state.</p></div><button class="button button--primary" (click)="openCreate()">Add battery</button></header>
    @if (loading()) { <app-page-state kind="loading" title="Loading batteries" message="Retrieving storage assets…" /> } @else if (error()) { <app-page-state kind="error" title="Could not load batteries" [message]="error()" (retry)="load()" /> } @else if (!batteries().length) { <app-page-state kind="empty" title="No batteries" message="Add a storage asset to begin monitoring it." /> } @else { <section class="card-grid">@for (battery of batteries(); track battery.id) { <article class="asset-card"><div class="asset-card__top"><div class="battery-gauge" [style.--charge.%]="battery.currentChargePercent"><span>{{ battery.currentChargePercent }}%</span></div><span [class]="battery.status === 'ONLINE' ? 'badge badge--success' : 'badge badge--warning'">{{ battery.status }}</span></div><h2>{{ battery.name }}</h2><p>{{ battery.identifier }} · {{ battery.siteName }}</p><dl><div><dt>Stored</dt><dd>{{ battery.currentStoredEnergyKwh }} kWh</dd></div><div><dt>Capacity</dt><dd>{{ battery.capacityKwh }} kWh</dd></div><div><dt>Updated</dt><dd>{{ battery.lastUpdatedAt | date:'short' }}</dd></div></dl><div class="asset-card__actions"><button class="button button--quiet button--small" (click)="openEdit(battery)">Edit</button><button class="button button--danger button--small" (click)="confirmDelete.set(battery)">Delete</button></div></article> }</section> }
    @if (editing()) { <div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><div class="modal__header"><h2>{{ editing()?.id ? 'Edit battery' : 'Add battery' }}</h2><button class="icon-button" aria-label="Close" (click)="editing.set(null)">×</button></div><form [formGroup]="form" (ngSubmit)="save()" class="form-grid"><label class="field"><span>Identifier</span><input formControlName="identifier" appModalAutofocus /></label><label class="field"><span>Name</span><input formControlName="name" /></label><label class="field"><span>Site</span><select formControlName="siteId">@for (site of sites(); track site.id) { <option [value]="site.id">{{ site.name }}</option> }</select></label><label class="field"><span>Status</span><select formControlName="status">@for (status of statuses; track status) { <option [value]="status">{{ status }}</option> }</select></label><label class="field"><span>Capacity (kWh)</span><input type="number" min="0.001" step="0.1" formControlName="capacityKwh" /></label><label class="field"><span>Charge (%)</span><input type="number" min="0" max="100" step="0.1" formControlName="currentChargePercent" /></label><label class="field"><span>Stored energy (kWh)</span><input type="number" min="0" step="0.1" formControlName="currentStoredEnergyKwh" /></label><label class="field"><span>Last updated</span><input type="datetime-local" formControlName="lastUpdatedAt" /></label><div class="modal__actions field--wide"><button class="button button--secondary" type="button" (click)="editing.set(null)">Cancel</button><button class="button button--primary" type="submit" [disabled]="saving()">{{ saving() ? 'Saving…' : 'Save battery' }}</button></div></form></section></div> }
    @if (confirmDelete(); as battery) { <div class="modal-backdrop"><section class="modal modal--small" role="alertdialog"><h2>Delete {{ battery.name }}?</h2><p>This removes the battery record if no related data prevents deletion.</p><div class="modal__actions"><button class="button button--secondary" (click)="confirmDelete.set(null)">Cancel</button><button class="button button--danger" (click)="remove(battery)">Delete battery</button></div></section></div> }
  `,
})
export class AdminBatteries {
  private readonly api = inject(AdminApiService); private readonly toast = inject(ToastService);
  readonly statuses = STATUSES; readonly batteries = signal<Battery[]>([]); readonly sites = signal<Site[]>([]); readonly loading = signal(true); readonly saving = signal(false); readonly error = signal(''); readonly editing = signal<Partial<Battery> | null>(null); readonly confirmDelete = signal<Battery | null>(null);
  readonly form = new FormGroup({ identifier: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(100)] }), name: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(150)] }), siteId: new FormControl<number | null>(null, [Validators.required]), capacityKwh: new FormControl<number | null>(null, [Validators.required, Validators.min(0.001)]), status: new FormControl<BatteryStatus>('ONLINE', { nonNullable: true }), currentChargePercent: new FormControl<number | null>(null, [Validators.required, Validators.min(0), Validators.max(100)]), currentStoredEnergyKwh: new FormControl<number | null>(null, [Validators.required, Validators.min(0)]), lastUpdatedAt: new FormControl('', { nonNullable: true, validators: [Validators.required] }) });
  constructor() { this.load(); }
  load(): void { this.loading.set(true); forkJoin({ batteries: this.api.batteries(), sites: this.api.sites() }).subscribe({ next: ({ batteries, sites }) => { this.batteries.set(batteries.content); this.sites.set(sites.content); this.loading.set(false); }, error: (error: unknown) => { this.error.set(apiErrorMessage(error)); this.loading.set(false); } }); }
  openCreate(): void { this.editing.set({}); this.form.reset({ identifier: '', name: '', siteId: this.sites()[0]?.id ?? null, capacityKwh: null, status: 'ONLINE', currentChargePercent: 0, currentStoredEnergyKwh: 0, lastUpdatedAt: localDate(new Date().toISOString()) }); }
  openEdit(battery: Battery): void { this.editing.set(battery); this.form.reset({ identifier: battery.identifier, name: battery.name, siteId: battery.siteId, capacityKwh: battery.capacityKwh, status: battery.status, currentChargePercent: battery.currentChargePercent, currentStoredEnergyKwh: battery.currentStoredEnergyKwh, lastUpdatedAt: localDate(battery.lastUpdatedAt) }); }
  closeOverlay(): void { this.editing.set(null); this.confirmDelete.set(null); }
  save(): void { this.form.markAllAsTouched(); const value = this.form.getRawValue(); const current = this.editing(); if (this.form.invalid || !current || value.siteId === null || value.capacityKwh === null || value.currentChargePercent === null || value.currentStoredEnergyKwh === null) return; const request: BatteryRequest = { ...value, siteId: value.siteId, capacityKwh: value.capacityKwh, currentChargePercent: value.currentChargePercent, currentStoredEnergyKwh: value.currentStoredEnergyKwh, lastUpdatedAt: new Date(value.lastUpdatedAt).toISOString() }; this.saving.set(true); const call = current.id ? this.api.updateBattery(current.id, request) : this.api.createBattery(request); call.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.toast.show(`Battery ${current.id ? 'updated' : 'created'}.`, 'success'); this.editing.set(null); this.load(); }, error: (error: unknown) => this.toast.show(apiErrorMessage(error), 'error') }); }
  remove(battery: Battery): void { this.api.deleteBattery(battery.id).subscribe({ next: () => { this.toast.show('Battery deleted.', 'success'); this.confirmDelete.set(null); this.load(); }, error: (error: unknown) => this.toast.show(apiErrorMessage(error), 'error') }); }
}
