import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { Device, DeviceRequest, DeviceStatus, DeviceType, Site } from '../../../core/models/api.models';
import { AdminApiService } from '../../../core/services/admin-api.service';
import { apiErrorMessage } from '../../../core/services/http-error';
import { ToastService } from '../../../core/services/toast.service';
import { ModalAutofocus } from '../../../shared/ui/modal-autofocus';
import { PageState } from '../../../shared/ui/page-state';

const TYPES: DeviceType[] = ['SOLAR_INVERTER', 'SMART_METER', 'BATTERY_CONTROLLER', 'WEATHER_SENSOR'];
const STATUSES: DeviceStatus[] = ['ONLINE', 'OFFLINE', 'MAINTENANCE', 'RETIRED'];
function localDate(value: string | null): string { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

@Component({
  selector: 'app-admin-devices', imports: [ReactiveFormsModule, DatePipe, PageState, ModalAutofocus],
  host: { '(document:keydown.escape)': 'closeOverlay()' },
  template: `
    <header class="page-header"><div><span class="eyebrow">Field equipment</span><h1>Devices</h1><p>Manage inverters, meters, controllers and weather sensors.</p></div><button class="button button--primary" type="button" (click)="openCreate()">Add device</button></header>
    <section class="filter-bar" aria-label="Device filters"><label><span>Status</span><select [formControl]="statusFilter" (change)="load()"><option value="">All statuses</option>@for (status of statuses; track status) { <option [value]="status">{{ status }}</option> }</select></label><label><span>Type</span><select [formControl]="typeFilter" (change)="load()"><option value="">All types</option>@for (type of types; track type) { <option [value]="type">{{ type }}</option> }</select></label><label><span>Site</span><select [formControl]="siteFilter" (change)="load()"><option value="">All sites</option>@for (site of sites(); track site.id) { <option [value]="site.id">{{ site.name }}</option> }</select></label></section>
    @if (loading()) { <app-page-state kind="loading" title="Loading devices" message="Retrieving field equipment…" /> } @else if (error()) { <app-page-state kind="error" title="Could not load devices" [message]="error()" (retry)="loadInitial()" /> } @else if (!devices().length) { <app-page-state kind="empty" title="No devices found" message="No equipment matches these filters." /> } @else {
      <section class="panel panel--table"><div class="table-scroll"><table><thead><tr><th>Device</th><th>Type</th><th>Site</th><th>Status</th><th>Last seen</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>@for (device of devices(); track device.id) { <tr><td data-label="Device"><strong>{{ device.name }}</strong><small>{{ device.identifier }}</small></td><td data-label="Type">{{ label(device.type) }}</td><td data-label="Site">{{ device.siteName }}</td><td data-label="Status"><span [class]="statusClass(device.status)">{{ device.status }}</span></td><td data-label="Last seen">{{ device.lastSeenAt ? (device.lastSeenAt | date:'short') : 'Never' }}</td><td class="table-actions"><button class="button button--quiet button--small" type="button" (click)="openEdit(device)">Edit</button><button class="button button--danger button--small" type="button" (click)="confirmDelete.set(device)">Delete</button></td></tr> }</tbody></table></div><div class="pagination"><span>{{ total() }} devices</span><div><button class="button button--secondary button--small" [disabled]="page() === 0" (click)="page.update((v) => v - 1); load()">Previous</button><button class="button button--secondary button--small" [disabled]="page() + 1 >= totalPages()" (click)="page.update((v) => v + 1); load()">Next</button></div></div></section>
    }
    @if (editing()) { <div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="device-title"><div class="modal__header"><div><span class="eyebrow">Equipment record</span><h2 id="device-title">{{ editing()?.id ? 'Edit device' : 'Add device' }}</h2></div><button class="icon-button" aria-label="Close" (click)="editing.set(null)">×</button></div><form [formGroup]="form" (ngSubmit)="save()" class="form-grid">
      <label class="field"><span>Identifier</span><input formControlName="identifier" appModalAutofocus /></label><label class="field"><span>Name</span><input formControlName="name" /></label><label class="field"><span>Type</span><select formControlName="type">@for (type of types; track type) { <option [value]="type">{{ label(type) }}</option> }</select></label><label class="field"><span>Status</span><select formControlName="status">@for (status of statuses; track status) { <option [value]="status">{{ status }}</option> }</select></label><label class="field"><span>Site</span><select formControlName="siteId">@for (site of sites(); track site.id) { <option [value]="site.id">{{ site.name }}</option> }</select></label><label class="field"><span>Manufacturer</span><input formControlName="manufacturer" /></label><label class="field"><span>Model</span><input formControlName="model" /></label><label class="field"><span>Firmware</span><input formControlName="firmwareVersion" /></label><label class="field field--wide"><span>Last seen</span><input type="datetime-local" formControlName="lastSeenAt" /></label><div class="modal__actions field--wide"><button class="button button--secondary" type="button" (click)="editing.set(null)">Cancel</button><button class="button button--primary" type="submit" [disabled]="saving()">{{ saving() ? 'Saving…' : 'Save device' }}</button></div>
      </form></section></div> }
    @if (confirmDelete(); as device) { <div class="modal-backdrop"><section class="modal modal--small" role="alertdialog" aria-modal="true"><h2>Delete {{ device.name }}?</h2><p>This permanently removes the device record.</p><div class="modal__actions"><button class="button button--secondary" (click)="confirmDelete.set(null)">Cancel</button><button class="button button--danger" (click)="remove(device)">Delete device</button></div></section></div> }
  `,
})
export class AdminDevices {
  private readonly api = inject(AdminApiService); private readonly toast = inject(ToastService);
  readonly types = TYPES; readonly statuses = STATUSES; readonly devices = signal<Device[]>([]); readonly sites = signal<Site[]>([]); readonly loading = signal(true); readonly saving = signal(false); readonly error = signal(''); readonly editing = signal<Partial<Device> | null>(null); readonly confirmDelete = signal<Device | null>(null); readonly page = signal(0); readonly totalPages = signal(0); readonly total = signal(0);
  readonly statusFilter = new FormControl<DeviceStatus | ''>('', { nonNullable: true }); readonly typeFilter = new FormControl<DeviceType | ''>('', { nonNullable: true }); readonly siteFilter = new FormControl<number | ''>('', { nonNullable: true });
  readonly form = new FormGroup({ identifier: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(100)] }), name: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(150)] }), type: new FormControl<DeviceType>('SOLAR_INVERTER', { nonNullable: true }), status: new FormControl<DeviceStatus>('ONLINE', { nonNullable: true }), siteId: new FormControl<number | null>(null, [Validators.required]), manufacturer: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(100)] }), model: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(100)] }), firmwareVersion: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(100)] }), lastSeenAt: new FormControl('', { nonNullable: true }) });
  constructor() { this.loadInitial(); }
  loadInitial(): void { this.loading.set(true); forkJoin({ sites: this.api.sites(), devices: this.api.devices() }).subscribe({ next: ({ sites, devices }) => { this.sites.set(sites.content); this.setPage(devices); this.loading.set(false); }, error: (error: unknown) => { this.error.set(apiErrorMessage(error)); this.loading.set(false); } }); }
  load(): void { this.loading.set(true); this.api.devices({ page: this.page(), status: this.statusFilter.value, type: this.typeFilter.value, siteId: this.siteFilter.value || null }).subscribe({ next: (result) => { this.setPage(result); this.loading.set(false); }, error: (error: unknown) => { this.error.set(apiErrorMessage(error)); this.loading.set(false); } }); }
  openCreate(): void { this.editing.set({}); this.form.reset({ identifier: '', name: '', type: 'SOLAR_INVERTER', status: 'ONLINE', siteId: this.sites()[0]?.id ?? null, manufacturer: '', model: '', firmwareVersion: '', lastSeenAt: '' }); }
  openEdit(device: Device): void { this.editing.set(device); this.form.reset({ identifier: device.identifier, name: device.name, type: device.type, status: device.status, siteId: device.siteId, manufacturer: device.manufacturer ?? '', model: device.model ?? '', firmwareVersion: device.firmwareVersion ?? '', lastSeenAt: localDate(device.lastSeenAt) }); }
  closeOverlay(): void { this.editing.set(null); this.confirmDelete.set(null); }
  save(): void { this.form.markAllAsTouched(); if (this.form.invalid || this.saving()) return; const value = this.form.getRawValue(); const current = this.editing(); if (!current || value.siteId === null) return; const request: DeviceRequest = { ...value, siteId: value.siteId, manufacturer: value.manufacturer || null, model: value.model || null, firmwareVersion: value.firmwareVersion || null, lastSeenAt: value.lastSeenAt ? new Date(value.lastSeenAt).toISOString() : null }; this.saving.set(true); const call = current.id ? this.api.updateDevice(current.id, request) : this.api.createDevice(request); call.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.toast.show(`Device ${current.id ? 'updated' : 'created'}.`, 'success'); this.editing.set(null); this.load(); }, error: (error: unknown) => this.toast.show(apiErrorMessage(error), 'error') }); }
  remove(device: Device): void { this.api.deleteDevice(device.id).subscribe({ next: () => { this.toast.show('Device deleted.', 'success'); this.confirmDelete.set(null); this.load(); }, error: (error: unknown) => this.toast.show(apiErrorMessage(error), 'error') }); }
  label(value: string): string { return value.toLowerCase().replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
  statusClass(status: DeviceStatus): string { return status === 'ONLINE' ? 'badge badge--success' : status === 'OFFLINE' ? 'badge badge--error' : status === 'MAINTENANCE' ? 'badge badge--warning' : 'badge badge--muted'; }
  private setPage(result: { content: Device[]; totalElements: number; totalPages: number }): void { this.devices.set(result.content); this.total.set(result.totalElements); this.totalPages.set(result.totalPages); }
}
