import { DatePipe, DecimalPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { Alert, Battery, EnergyReading, EnergySummary, Site } from '../../../core/models/api.models';
import { HomeownerApiService } from '../../../core/services/homeowner-api.service';
import { apiErrorMessage } from '../../../core/services/http-error';
import { PageState } from '../../../shared/ui/page-state';

@Component({
  selector: 'app-homeowner-dashboard', imports: [RouterLink, DatePipe, DecimalPipe, PageState],
  template: `
    <header class="page-header"><div><span class="eyebrow">Current overview</span><h1>Your energy system</h1><p>Live totals use the latest 24-hour range provided by the Solaris backend.</p></div><a class="button button--secondary" routerLink="/homeowner/reports">View reports</a></header>
    @if (loading()) { <app-page-state kind="loading" title="Loading your system" message="Collecting sites, energy, storage and alert status…" /> } @else if (error()) { <app-page-state kind="error" title="Could not load dashboard" [message]="error()" (retry)="load()" /> } @else {
      <section class="system-banner"><div><span class="eyebrow eyebrow--light">Portfolio status</span><h2>{{ sites().length ? sites().length + (sites().length === 1 ? ' active site' : ' active sites') : 'No assigned sites' }}</h2><p>{{ sites().length ? 'Your connected solar portfolio is available for monitoring.' : 'An administrator must assign a solar site to your account.' }}</p></div><div class="system-banner__stat"><span>Unread alerts</span><strong>{{ unreadAlerts() }}</strong></div></section>
      <section class="metric-grid" aria-label="24 hour energy summary"><article class="metric-card metric-card--production"><div class="metric-card__head"><span>Production</span><span class="trend-mark">↑</span></div><strong>{{ summary()?.productionKwh | number:'1.1-2' }} <small>kWh</small></strong><small>Last 24 hours</small></article><article class="metric-card"><div class="metric-card__head"><span>Consumption</span><span class="metric-card__symbol">C</span></div><strong>{{ summary()?.consumptionKwh | number:'1.1-2' }} <small>kWh</small></strong><small>Last 24 hours</small></article><article class="metric-card"><div class="metric-card__head"><span>Grid import</span><span class="metric-card__symbol">↓</span></div><strong>{{ summary()?.gridImportKwh | number:'1.1-2' }} <small>kWh</small></strong><small>Energy received</small></article><article class="metric-card"><div class="metric-card__head"><span>Grid export</span><span class="metric-card__symbol">↑</span></div><strong>{{ summary()?.gridExportKwh | number:'1.1-2' }} <small>kWh</small></strong><small>Energy returned</small></article></section>
      <section class="content-grid content-grid--two-thirds"><article class="panel"><div class="panel__header"><div><span class="eyebrow">Recent telemetry</span><h2>Latest readings</h2></div><a class="text-link" routerLink="/homeowner/energy">Explore energy →</a></div>@if (readings().length) { <div class="reading-list">@for (reading of readings(); track reading.id) { <div><span class="reading-list__time">{{ reading.timestamp | date:'shortTime' }}</span><span><strong>{{ reading.siteName }}</strong><small>{{ reading.deviceIdentifier }}</small></span><span class="reading-list__value">{{ reading.productionKwh | number:'1.1-2' }} kWh<small>production</small></span></div> }</div> } @else { <div class="compact-empty"><strong>No readings in the last 24 hours</strong><span>Telemetry will appear here when available.</span></div> }</article>
        <article class="panel"><div class="panel__header"><div><span class="eyebrow">Storage</span><h2>Battery status</h2></div><a class="text-link" routerLink="/homeowner/storage">Details →</a></div>@if (batteries().length) { @for (battery of batteries().slice(0, 3); track battery.id) { <div class="battery-summary"><div><strong>{{ battery.name }}</strong><small>{{ battery.siteName }} · {{ battery.status }}</small></div><strong>{{ battery.currentChargePercent }}%</strong><div class="progress" [attr.aria-label]="battery.name + ' charge'" role="progressbar" aria-valuemin="0" aria-valuemax="100" [attr.aria-valuenow]="battery.currentChargePercent"><span [style.width.%]="battery.currentChargePercent"></span></div></div> } } @else { <div class="compact-empty"><strong>No battery assigned</strong><span>Storage assets will appear after configuration.</span></div> }</article>
      </section>
      <section class="panel"><div class="panel__header"><div><span class="eyebrow">Needs attention</span><h2>Recent alerts</h2></div><a class="text-link" routerLink="/homeowner/alerts">All alerts →</a></div>@if (alerts().length) { <div class="alert-list alert-list--compact">@for (alert of alerts(); track alert.id) { <article class="alert-row" [class.alert-row--unread]="!alert.read"><span [class]="'severity-mark severity-mark--' + alert.severity.toLowerCase()"></span><div><strong>{{ label(alert.type) }}</strong><p>{{ alert.message }}</p><small>{{ alert.createdAt | date:'medium' }}</small></div></article> }</div> } @else { <div class="compact-empty"><strong>No current alerts</strong><span>Your system has no alerts in this view.</span></div> }</section>
    }
  `,
})
export class HomeownerDashboard {
  private readonly api = inject(HomeownerApiService);
  readonly loading = signal(true); readonly error = signal(''); readonly sites = signal<Site[]>([]); readonly summary = signal<EnergySummary | null>(null); readonly readings = signal<EnergyReading[]>([]); readonly batteries = signal<Battery[]>([]); readonly alerts = signal<Alert[]>([]); readonly unreadAlerts = signal(0);
  constructor() { this.load(); }
  load(): void { this.loading.set(true); this.error.set(''); forkJoin({ sites: this.api.sites(), summary: this.api.energySummary(), readings: this.api.energyReadings({ size: 5 }), batteries: this.api.storageStatus(), alerts: this.api.alerts({ size: 4, read: false }) }).subscribe({ next: ({ sites, summary, readings, batteries, alerts }) => { this.sites.set(sites); this.summary.set(summary); this.readings.set(readings.content); this.batteries.set(batteries); this.alerts.set(alerts.content); this.unreadAlerts.set(alerts.totalElements); this.loading.set(false); }, error: (error: unknown) => { this.error.set(apiErrorMessage(error)); this.loading.set(false); } }); }
  label(value: string): string { return value.toLowerCase().replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
}
